In [1]:
import pandas as pd
import numpy as np

In [2]:
political_dataset=pd.read_csv("../resources/kenya_political_tweets.csv")

## 1. How many rows and columns are in the dataset?

In [3]:
political_dataset.shape

(11723, 16)

- The dataset has 11723 rows and 16 columns

In [4]:
political_dataset.head(5)

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet
0,1396091006030856192,Doomster,Utopia slums,"Alt-left, liberal, pronoun:them",2009-08-23 12:22:53,309,907,8050,False,2021-05-22 13:10:08,@PrettyAmmina The change to the new blue unifo...,NaN,Twitter Web App,0.0,0.0,False
1,1395981137764397056,Unruly 🗯,Morayfield,I don't know what you thought this was gonna b...,2011-04-20 19:35:54,1053,523,5279,False,2021-05-22 05:53:33,I think it's now safe to say President Uhuru K...,NaN,Twitter for Android,0.0,0.0,False
2,1395433210490798082,Khavin,Nairobi,CCTV installation and MAINTENANCE technician. ...,2020-02-11 04:52:44,4202,3735,29563,False,2021-05-20 17:36:17,@_CrazyKenyan President Uhuru Kenyatta bribed ...,['bbinonsense'],Twitter Web App,0.0,1.0,False
3,1394739630898044931,Lecturer🇰🇪💥,Eldoret,President Kenyatta's critic.William Samoei Rut...,2020-01-23 19:10:51,774,1467,4150,False,2021-05-18 19:40:15,"As @HonMoses_Kuria has just been saying,Presid...",NaN,Twitter for Android,0.0,0.0,False
4,1394561455471661057,Lecturer🇰🇪💥,Eldoret,President Kenyatta's critic.William Samoei Rut...,2020-01-23 19:10:51,774,1467,4150,False,2021-05-18 07:52:15,David Murathe the KEMSA thief and President Uh...,NaN,Twitter for Android,2.0,1.0,False

In [5]:
political_dataset.tail(5)

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet
11718,1403061559727951875,Nation Africa,Kenya,"We are Nation. For customer care, 📨 support@na...",2009-03-23 10:15:38,2437840,268,2352,True,2021-06-10 18:48:38,Preparations are in top gear for the coronatio...,NaN,TweetDeck,11.0,102.0,False
11719,1403060195077545985,Joel Mulwa Njenga Jr 🇰🇪,"Nyahururu, Kenya",Laikipia general (Hustler)\npolitics and footb...,2015-08-20 11:31:10,12398,9973,30836,False,2021-06-10 18:43:12,"""I managed to kick William Ruto out of Jubilee...",NaN,Twitter for Android,0.0,0.0,False
11720,1403059933239721988,Mutugi,Nairobi kenya,A Clone Of Socrates And Einstein.,2021-03-29 13:40:13,383,383,1596,False,2021-06-10 18:42:10,If William Ruto and Uhuru Kenyatta could not m...,NaN,Twitter for Android,0.0,6.0,False
11721,1403059390568087556,TV47 Kenya,"Nairobi, Kenya","TV47 is a local, free-to-air television statio...",2015-02-13 08:17:41,29513,527,13789,False,2021-06-10 18:40:00,DP William Ruto has criticized proponents of B...,NaN,Twitter Web App,0.0,3.0,False
11722,1403057818765254657,Justin,NaN,Optimist Educator| African History Researcher.,2019-07-03 05:07:34,1777,1666,406,False,2021-06-10 18:33:46,"In the early 90s, companies used to look for g...",NaN,Twitter for Android,0.0,5.0,False

In [6]:
political_dataset.describe()

           retweets     favorites
count  11721.000000  11721.000000
mean       7.571538     42.103234
std       60.232891    317.674889
min        0.000000      0.000000
25%        0.000000      0.000000
50%        0.000000      2.000000
75%        2.000000      8.000000
max     3011.000000  16302.000000

## 2. What datatypes are contained in the dataset?

In [7]:
political_dataset.dtypes

id                      str
user_name               str
user_location           str
user_description        str
user_created            str
user_followers          str
user_friends            str
user_favourites         str
user_verified        object
date                    str
text                    str
hashtags                str
source                  str
retweets            float64
favorites           float64
is_retweet           object
dtype: object

- The datatypes vary from strings, to objects to floats

## 3. Is the Dataset Complete?

In [8]:
political_dataset.isna().sum()

id                      0
user_name               0
user_location        2484
user_description      993
user_created            1
user_followers          1
user_friends            1
user_favourites         1
user_verified           2
date                    1
text                    1
hashtags            10549
source                  1
retweets                2
favorites               2
is_retweet              2
dtype: int64

- The dataset is not complete as there are missing values in each column

## 4. Slice out the first 15 rows and last 20 rows and merge them into a new dataframe titled `df_sample`. Display this new dataframe.

In [9]:
set_head=political_dataset.head(15)
set_tail=political_dataset.tail(20)

In [10]:
df_sample=pd.concat([set_head,set_tail])

In [11]:
df_sample.shape

(35, 16)

In [12]:
df_sample

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet
0,1396091006030856192,Doomster,Utopia slums,"Alt-left, liberal, pronoun:them",2009-08-23 12:22:53,309,907,8050,False,2021-05-22 13:10:08,@PrettyAmmina The change to the new blue unifo...,NaN,Twitter Web App,0.0,0.0,False
1,1395981137764397056,Unruly 🗯,Morayfield,I don't know what you thought this was gonna b...,2011-04-20 19:35:54,1053,523,5279,False,2021-05-22 05:53:33,I think it's now safe to say President Uhuru K...,NaN,Twitter for Android,0.0,0.0,False
2,1395433210490798082,Khavin,Nairobi,CCTV installation and MAINTENANCE technician. ...,2020-02-11 04:52:44,4202,3735,29563,False,2021-05-20 17:36:17,@_CrazyKenyan President Uhuru Kenyatta bribed ...,['bbinonsense'],Twitter Web App,0.0,1.0,False
3,1394739630898044931,Lecturer🇰🇪💥,Eldoret,President Kenyatta's critic.William Samoei Rut...,2020-01-23 19:10:51,774,1467,4150,False,2021-05-18 19:40:15,"As @HonMoses_Kuria has just been saying,Presid...",NaN,Twitter for Android,0.0,0.0,False
4,1394561455471661057,Lecturer🇰🇪💥,Eldoret,President Kenyatta's critic.William Samoei Rut...,2020-01-23 19:10:51,774,1467,4150,False,2021-05-18 07:52:15,David Murathe the KEMSA thief and President Uh...,NaN,Twitter for Android,2.0,1.0,False
5,1394334198417215493,Lecturer🇰🇪💥,Eldoret,President Kenyatta's critic.William Samoei Rut...,2020-01-23 19:10:51,774,1467,4150,False,2021-05-17 16:49:13,The Kenyan Senate despite having several elite...,NaN,Twitter for Android,0.0,0.0,False
6,1394014196610781189,Lecturer🇰🇪💥,Eldoret,President Kenyatta's critic.William Samoei Rut...,2020-01-23 19:10:51,774,1467,4150,False,2021-05-16 19:37:38,Somebody tell CS Peter Munya to die before 202...,NaN,Twitter for Android,0.0,1.0,False
7,1393619973524832257,G.G Peter Atom,Nairobi,"God Gave me wisdom, empowered me to search for...",2011-10-06 08:19:42,117,308,1839,False,2021-05-15 17:31:08,ICC called him Mr. Kenyatta for they did not r...,NaN,Twitter for Android,0.0,0.0,False
8,1393618298684727298,Nyandarua County Government,Kenya,Official twitter account of Nyandarua County G...,2016-10-13 14:25:52,1926,170,361,False,2021-05-15 17:24:29,The leaders urged residents of the Central Reg...,NaN,Twitter for Android,0.0,0.0,False
9,1393615018642579461,Suleiman H Sandhere,Somaliland,8th president of the Republic of Somaliland. I...,2017-06-19 19:52:31,59,335,66,False,2021-05-15 17:11:27,Three leaders of Horn of Africa👇\n1. President...,NaN,Twitter for Android,0.0,0.0,False
10,1393611039552458763,Daudi,Kejani,Make choices that suit you,2019-06-28 08:08:55,1675,2615,4405,False,2021-05-15 16:55:38,President Uhuru Kenyatta considered Kisii Coun...,['KomeshaCorona'],Twitter for iPhone,0.0,0.0,False
11,1393610155632349190,mike miraj,Niarobi,NaN,2015-12-01 06:58:08,58,527,147,False,2021-05-15 16:52:07,@ngunjiriwambugu Can someone help me to answer...,NaN,Twitter for Android,0.0,0.0,False
12,1393610122119815171,Daudi,Kejani,Make choices that suit you,2019-06-28 08:08:55,1675,2615,4405,False,2021-05-15 16:51:59,This latest move shows President Uhuru Kenyatt...,NaN,Twitter for iPhone,0.0,0.0,False
13,1393606140454395906,Msafi,NaN,NaN,2020-06-21 11:43:36,10,32,1529,False,2021-05-15 16:36:10,@StateHouseKenya What u have done today my pre...,NaN,Twitter Web App,0.0,2.0,False
14,1393605303967571970,Fridah Mueni 😍,"Nairobi, Kenya","Nurse by profession, aspiring county women rep...",2018-12-10 09:09:38,5472,5638,22691,False,2021-05-15 16:32:51,President Uhuru Kenyatta considered Kisii Coun...,['KomeshaCorona'],Twitter Web App,1.0,1.0,False
11703,1403200319220195328,Nation Africa,Kenya,"We are Nation. For customer care, 📨 support@na...",2009-03-23 10:15:38,2437840,268,2352,True,2021-06-11 04:00:00,Preparations are in top gear for the coronatio...,NaN,TweetDeck,4.0,15.0,False
11704,1403194776187543552,John Wafula Khisa,"Usan, Scotland",Male,2016-01-26 08:23:30,337,1140,795,False,2021-06-11 03:37:59,We only have one man to Kibakilize this poor e...,NaN,Twitter for Android,1.0,2.0,False
11705,1403107234264014851,Mwakilishi.com,Kenya Diaspora,https://t.co/l2k3nsQgJu: Kenya Diaspora News L...,2009-09-14 22:01:43,3371,1136,42,False,2021-06-10 21:50:07,Murathe: My Work was to Kick Out Deputy Presid...,NaN,Twitter Web App,0.0,0.0,False
11706,1403106175223279630,Rogue Ndorobo PhD,Mlimwengu,PhD-Disaster Risk Mgmt. \nCritical Infrastruct...,2020-04-06 06:12:03,624,133,65,False,2021-06-10 21:45:55,Being crowned a kingpin seems the in- thing no...,NaN,Twitter for Android,3.0,9.0,False
11707,1403093650628874245,Tuko.co.ke,"Nairobi, Kenya",Follow TUKO for reliable breaking news on Poli...,2015-04-02 13:49:55,157529,3940,1575,True,2021-06-10 20:56:09,William Ruto hit out at the BBI process and sa...,NaN,Twitter Web App,0.0,11.0,False
11708,1403092179371925504,Enoch Cheruiyot..,NaN,NaN,2021-04-23 22:48:55,1099,859,5713,False,2021-06-10 20:50:18,"Maseno is in Kisumu, not Vihiga, Lands ministr...",NaN,Twitter for Android,0.0,1.0,False
11709,1403078485430652928,Abdiweli Duale,|Nairobi|kenya🇰🇪,Health and science freelance Journalist.| Medi...,2017-10-08 10:03:42,3059,3196,7103,False,2021-06-10 19:55:53,Preparations are in top gear as elders lay gro...,NaN,Twitter Web App,0.0,8.0,False
11710,1403075133628166144,Gabriel Oguda,"Nairobi, Kenya","'If you must bow, let it be to a lofty mountai...",2013-07-23 12:42:45,199517,1214,9930,False,2021-06-10 19:42:34,#NewsGang calling out Aden Duale for his comme...,['NewsGang'],Twitter for Android,123.0,722.0,False
11711,1403074906200358915,Keith,"Nairobi, Kenya",Your favourite #KOT economist ..\npart time ch...,2020-12-15 21:40:57,79,82,216,False,2021-06-10 19:41:40,With William Ruto. After william Ruto \nRun...,NaN,Twitter for Android,1.0,8.0,False
11712,1403073568867557379,Francis Ndirangu,Nairobi,A writer and sociologist.,2012-01-16 19:34:34,401,438,7338,False,2021-06-10 19:36:21,@WilliamsRuto Elders lay ground for William Ru...,NaN,Twitter Web App,0.0,0.0,False
11713,1403070118133915657,NTV Kenya,Nairobi,LIVE STREAM: https://t.co/Vp8SMcv7jV _________...,2009-03-23 11:30:40,2941714,321,9270,True,2021-06-10 19:22:38,Elders lay ground for Ruto's crowning as Kalen...,NaN,Hootsuite Inc.,44.0,448.0,False
11714,1403069213179355141,TheStarKenya,Kenya,Independent Fresh And Different! 🇰🇪\nWhatsApp:...,2011-07-27 11:55:33,1321926,511,812,True,2021-06-10 19:19:02,Deputy President William Ruto taken a slight a...,NaN,Echobox,10.0,63.0,False
11715,1403065235855089674,Daniel Oluoch,NaN,Karne hii ya 21 tukiongea kuhusu makabila si h...,2012-07-22 03:51:10,41,397,325,False,2021-06-10 19:03:14,@jabbyzo @mureithi_karani @njagi_keru @ahmedna...,NaN,Twitter for Android,0.0,1.0,False
11716,1403063054846341120,Enoch Cheruiyot..,NaN,NaN,2021-04-23 22:48:55,1099,859,5713,False,2021-06-10 18:54:34,"Kampala is beautiful, have you been there?\n\n...",NaN,Twitter for Android,3.0,103.0,False
11717,1403062181164421124,Kenyan Tribune,"Nairobi, Kenya",Kenya’s entertainment and breaking news blog,2017-06-16 17:13:59,3362,0,13,False,2021-06-10 18:51:06,Elders lay ground for William Ruto's crowning ...,NaN,Kenyan Tribune,0.0,0.0,False
11718,1403061559727951875,Nation Africa,Kenya,"We are Nation. For customer care, 📨 support@na...",2009-03-23 10:15:38,2437840,268,2352,True,2021-06-10 18:48:38,Preparations are in top gear for the coronatio...,NaN,TweetDeck,11.0,102.0,False
11719,1403060195077545985,Joel Mulwa Njenga Jr 🇰🇪,"Nyahururu, Kenya",Laikipia general (Hustler)\npolitics and footb...,2015-08-20 11:31:10,12398,9973,30836,False,2021-06-10 18:43:12,"""I managed to kick William Ruto out of Jubilee...",NaN,Twitter for Android,0.0,0.0,False
11720,1403059933239721988,Mutugi,Nairobi kenya,A Clone Of Socrates And Einstein.,2021-03-29 13:40:13,383,383,1596,False,2021-06-10 18:42:10,If William Ruto and Uhuru Kenyatta could not m...,NaN,Twitter for Android,0.0,6.0,False
11721,1403059390568087556,TV47 Kenya,"Nairobi, Kenya","TV47 is a local, free-to-air television statio...",2015-02-13 08:17:41,29513,527,13789,False,2021-06-10 18:40:00,DP William Ruto has criticized proponents of B...,NaN,Twitter Web App,0.0,3.0,False
11722,1403057818765254657,Justin,NaN,Optimist Educator| African History Researcher.,2019-07-03 05:07:34,1777,1666,406,False,2021-06-10 18:33:46,"In the early 90s, companies used to look for g...",NaN,Twitter for Android,0.0,5.0,False