In [1]:
!pip install datasets -q
import pandas as pd
import numpy as np
from datasets import load_dataset

hf_data = load_dataset("lusamaki/Fake_News_Detection_System_9K")
dataset = hf_data['train'].to_pandas()

dataset.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/94.0 [00:00<?, ?B/s]

train_dataset.csv:   0%|          | 0.00/1.64M [00:00<?, ?B/s]

test_dataset.csv:   0%|          | 0.00/705k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/6300 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2700 [00:00<?, ? examples/s]

,Unnamed: 0,tweet,label,text,language,contains_emoji
0,5266,@user @user So he only worked from June 1st to...,fact,worked june st alter presidential elections re...,sheng,True
1,4574,It s 61 days to 2022 general elections to end ...,fact,s days general elections end martharao sababu ...,sheng,False
2,96,@user Kenya Kwanza yaongezewa @user za tena,neutral,kenya kwanza yaongezewa za tena,Swahili,False
3,1967,There will be no need of panic\nAvoid incompet...,fact,need panicavoid incompetence vote wiselykenyad...,sheng,False
4,118,IEBC Kenya imeweka mbinu mbili kuu za kuwatamb...,fact,iebc kenya imeweka mbinu mbili kuu za kuwatamb...,Swahili,False

In [2]:
rows, cols = dataset.shape

print("Rows:", rows)
print("Columns:", cols)

Rows: 6300
Columns: 6

In [3]:
print(dataset.dtypes)

Unnamed: 0         int64
tweet             object
label             object
text              object
language          object
contains_emoji      bool
dtype: object

In [4]:
empty_per_col = dataset.isna().sum()
all_empty = empty_per_col.sum()

print(empty_per_col)
print("\nTotal empty cells:", all_empty)

if all_empty == 0:
    print("The dataset is complete.")
else:
    print(f"The dataset is incomplete. It is missing {all_empty} values.")

Unnamed: 0        0
tweet             0
label             0
text              0
language          0
contains_emoji    0
dtype: int64

Total empty cells: 0
The dataset is complete.

In [5]:
set_head = dataset.head(15)
set_tail = dataset.tail(20)

df_sample = pd.concat([set_head, set_tail])

print("Shape:", df_sample.shape)
df_sample

Shape: (35, 6)

,Unnamed: 0,tweet,label,text,language,contains_emoji
0,5266,@user @user So he only worked from June 1st to...,fact,worked june st alter presidential elections re...,sheng,True
1,4574,It s 61 days to 2022 general elections to end ...,fact,s days general elections end martharao sababu ...,sheng,False
2,96,@user Kenya Kwanza yaongezewa @user za tena,neutral,kenya kwanza yaongezewa za tena,Swahili,False
3,1967,There will be no need of panic\nAvoid incompet...,fact,need panicavoid incompetence vote wiselykenyad...,sheng,False
4,118,IEBC Kenya imeweka mbinu mbili kuu za kuwatamb...,fact,iebc kenya imeweka mbinu mbili kuu za kuwatamb...,Swahili,False
5,1521,@user Show us your tallying centre Bladfwakin ...,fact,tallying centre bladfwakin wewe,sheng,False
6,15992,youthagenda254 Oayouthkenya UN Women ChiromoHo...,neutral,youthagenda254 oayouthkenya women chiromohospg...,English,True
7,77,@user @user Tuliza familia uliyoua mwana wao k...,fake,tuliza familia uliyoua mwana wao kwanza,Swahili,False
8,2793,Mizani polls show TheODMparty Gubernatorial ca...,neutral,mizani polls theodmparty gubernatorial candida...,sheng,True
9,530,@user stop the theatrics and announce the winn...,neutral,stop theatrics announce winner able leaders ke...,English,False
10,3195,Leaders say no to corruption. EACCKenya IEBC K...,neutral,leaders corruption eacckenya iebc kenya ncic k...,sheng,False
11,176,SakajaJohnson WilliamsRuto Hongera kabisa,fact,sakajajohnson williamsruto hongera kabisa,Swahili,False
12,104,@user @user W@user jsckenya CJIEBC Kenya@user ...,neutral,w jsckenya cjiebc kenya kenya judiciary hautat...,Swahili,False
13,7948,Let’s get out and VOTE 💙 President @user DP @u...,neutral,lets vote president dp governor senator women ...,English,True
14,88,@user @user @user Na bado mtaongoja miaka ingi...,neutral,na bado mtaongoja miaka ingine tano,Swahili,False
6280,8022,KenyaDecides2022\nJust voted buruu the karaa v...,neutral,kenyadecides2022just voted buruu karaa voted c...,English,True
6281,106,citize@user kenya kenya decides 2022 KenyasCho...,fact,citize kenya kenya decides kenyaschoice2022 sa...,Swahili,False
6282,18995,So unfortunate that Baba has never lost any of...,fake,unfortunate baba lost elections rigged s time ...,English,False
6283,1111,Assmio supporters will not vote in masses beca...,fake,assmio supporters vote masses because1 countin...,sheng,False
6284,178,milkawangui12 Gvn ni susankihika senator ~ Tab...,fake,milkawangui12 gvn ni susankihika senator tabit...,Swahili,False
6285,11591,blongwe kachwanya TonwaTai You and I understan...,fake,blongwe kachwanya tonwatai understand english ...,English,True
6286,116,Vijana wa Naivasha wameamua kuweka amani sasa ...,fact,vijana wa naivasha wameamua kuweka amani sasa ...,Swahili,False
6287,116,Vijana wa Naivasha wameamua kuweka amani sasa ...,fact,vijana wa naivasha wameamua kuweka amani sasa ...,Swahili,False
6288,4073,Now we are getting somewhere Real substantive ...,neutral,getting real substantive issues praising chebu...,sheng,False
6289,148,e odeo Hiyo kazi na ya IEBC hakuna difference....,fake,e odeo hiyo kazi na ya iebc hakuna difference ...,Swahili,False
6290,99,@user Kazi n Kazi tumeanza https://t.co/jwcu4Z...,fact,kazi n kazi tumeanza,Swahili,False
6291,3147,Keep this and retrieve in 15 days. The best th...,neutral,retrieve days best achieve percent kura merufm...,sheng,False
6292,16,@user @user Mungu n mwema,neutral,mungu n mwema,Swahili,False
6293,9366,DCI Kenya @user @user kenya KTNNewsKE is this ...,fact,dci kenya kenya ktnnewske information clear fa...,English,True
6294,3636,Over to you IEBC Kenya let s know what your up...,fake,iebc kenya let s know upto tujue tuu na mapema...,sheng,False
6295,4922,If only Kenya had a petition website. We would...,fact,kenya petition website vote boatymcboatface mo...,English,False
6296,184,WilliamsRuto Kura umeshindua wewe,fake,williamsruto kura umeshindua wewe,Swahili,False
6297,9539,mose @user m Trying to twist the statement to ...,fake,mose m trying twist statement agents shallow a...,English,False
6298,4451,@user Karua ndio kigezo kwa kalonzo kujiunga n...,fake,karua ndio kigezo kwa kalonzo kujiunga na azim...,sheng,False
6299,896,A rare picture of what will be hanging in all ...,neutral,rare picture hanging public private offices bu...,English,False